# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.07.062704'

RELEASE_GIT_HEAD = '5b1ca3b508652644959fe18f3cb61bc550c28f84'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'viviedu/yt-dlp'

ORIGIN = 'viviedu/yt-dlp'

_pkg_version = '2024.08.07.062704'
